### ISSUE TITLE
Project won't build nor will it "Show Problems" in console

### ISSUE THREAD

**Issue by Kingeh** [KTXSoftware/VelvetWorm#2]
I don't know if it's some missing libraries or kha version incompatibility. The console doesn't show any output. Using windows 8.1 64bit. I use the kha version from github in Kode Studio. 

![screenshot_1](https://user-images.githubusercontent.com/2022298/45057355-b3535a00-b095-11e8-805f-97dc7bb7fa58.png)

**Comment by Kingeh** [comment]
It works when i init a new project and copy all the files from the game into the newly created folder. Only difference is build folder that was created inside my new project.

**Comment by RobDangerous** [comment]
You downloaded the sample without the --recursive option, didn't you? That leaves an empty Kha subdir in the project which Kode Studio tries to use but which of course doesn't work too well. It's on my todo list for the next Kode Studio version to detect that situation.

**Comment by Kingeh** [comment]
I downloaded as zip file

**Comment by RobDangerous** [comment]
Same problem, GitHub's download zip feature doesn't support submodules and puts an empty Kha dir in. Just delete it and it should work.

**Comment by Kingeh** [comment]
Okay thanks it works now! :)
